### ISSUE TITLE
where the assets.js came from?

### ISSUE THREAD

**Issue by telfDavid** [chronoDave/tic-bundle#15]
it isn't specified :(

**Comment by chronoDave** [comment]
`assets.js` is just an example file used to demonstrate the ability to bundle files that contain assets. There's an [example](https://github.com/chronoDave/tic-bundle#example) that shows the content of `assets.js`.

The idea is that you create assets in a separate cart and copy those assets over into `assets.js` so that you can bundle both code and assets into one. This way you don't have to copy+paste your bundled code into a separate cartridge manually.
